server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost
    password: foobared123
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 10
        min-idle: 5
        max-wait: -1
    timeout: 3000






mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# Redis 自定义Key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超时时间

jwt:
  expiration: 3600 #JWT的超期限时间(60*60*24)
  secret: oyd588 #JWT加解密使用的密钥
  tokenHeader: Authorization #JWT存储的请求头
  tokenHead: Bearer  #JWT负载中拿到开头
